version: '3'

services:

  source:
    build: ./source
    environment:
      KAFKA_BROKER_URL: broker:9092
      TRANSACTIONS_TOPIC: transactions
      TRANSACTIONS_PER_SECOND: 1000

networks:
  default:
    external:
      name: kafka-network
